spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-getway}

zuul:
  routes:
    tasks-service:
      path: /api/tasks-service/**
      url:  http://${TASKS_SERVICE_HOST:localhost}:${TASKS_SERVICE_PORT:8080}/api
    users-service:
        path: /api/users-service/**
        url:  http://${USERS_SERVICE_HOST:localhost}:${USERS_SERVICE_PORT:8080}/api
    register-service:
      path: /api/register-service/**
      url: http://${REGISTER_SERVICE_HOST:localhost}:${REGISTER_SERVICE_PORT:8080}/api

api-getway-url: http://${API_GETWAY_HOST:localhost}:${API_GETWAY_PORT:8080}
auth-login-url: http://${AUTH_LOGIN_CHECK_URL:localhost:8080/api/login}
tasks-service-tasks-url: http://${TASKS_SERV_TASKS_URL:localhost:8080/api/tasks}
users-service-url: http://${USERS_SERV_URL:localhost:8080/api/users}
projects-service-url: http://${PROJECTS_SERV_URL:localhost:8080}
register-service-url: http://${REGISTER_SERVICE_URL:http://localhost:8080/api/register}

server:
  port: ${SERVER_PORT:8080}

url:
  host: http://localhost
  port:
    register: 8081
  path:
    register: /api/register